site_name: wwwillchen Personal Blog
theme:
  name: material
  font:
    text: Inter

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: mesop-light
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: mesop-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - navigation.path
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.highlight

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_dir: .
  - search
